<? php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<title>Saadia Gabriel</title>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">';
echo '<!-- Add icon library -->';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">';
echo '<body>';
echo '';
echo '';
echo '<!-- Navbar -->';
echo '<div class="w3-bar w3-xlarge w3-black w3-card-2">';
echo '<a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>';
echo '<a href="cv_updated.pdf" class="w3-bar-item w3-button w3-padding-large w3-hide-small">CV</a>';
echo '</div>';
echo '';
echo '<!-- Navbar on small screens -->';
echo '<div id="navDemo" class="w3-bar-block w3-black w3-hide w3-hide-large w3-hide-medium w3-top">';
echo '<a href="cv_updated.pdf" class="w3-bar-item w3-button w3-padding-large">CV</a>';
echo '</div>';
echo '';
echo '<style>';
echo '#myAnimation {';
echo 'width: 22%;';
echo 'height: 27%;';
echo 'position: absolute;';
echo 'top: 12px;';
echo 'background-image: url('crane3.jpg');';
echo 'background-size: 100%;';
echo 'opacity: .4;';
echo '}';
echo '#myAnimation2 {';
echo 'width: 22%;';
echo 'height: 27%;';
echo 'position: absolute;';
echo 'left:1280px;';
echo 'bottom: 110px;';
echo 'background-image: url('crane4.jpg');';
echo 'background-size: 100%;';
echo 'opacity: .4;';
echo '}';
echo 'body {';
echo 'background-color: linen;';
echo 'background-size : 150%;';
echo '}';
echo '';
echo 'h1 {';
echo 'color: maroon;';
echo 'margin-left: 40px;';
echo '}';
echo '';
echo '/* Centered text */';
echo '.centered {';
echo 'background-color: linen;';
echo 'opacity:.6;';
echo 'position: absolute;';
echo 'top: 10%;';
echo 'right: 40%;';
echo '}';
echo '';
echo 'p {';
echo 'font-size: 16px;';
echo 'font-size: 1.6vh;';
echo '}';
echo 'ul{';
echo 'font-size: 16px;';
echo 'font-size: 1.6vh;';
echo '}';
echo '</style>';
echo '';
echo '<div class="container">';
echo '<div class="w3-content w3-display-container w3-text-black" style="height:100%;">';
echo '<img src="image.jpg" alt="Norway" style="width:60%;">';
echo '<div class="centered"><h1>Saadia Gabriel</h1></div>';
echo '</div>';
echo '<div class="w3-display-topright w3-container w3-blue-gray" style="overflow: auto; position: fixed; top:5%;height: 50%; width: 40%;">';
echo '<p>Hi! I'm a second-year graduate student in the Paul G. Allen School of Computer Science &amp; Engineering at the University of Washington. I am advised by <a href="https://homes.cs.washington.edu/~yejin/">Prof. Yejin Choi</a>. My research area is natural language understanding and generation. I'm excited about machine learning techniques and deep-learning models for social commonsense and logical reasoning in text.</p>';
echo '</div>';
echo '<div class="w3-display-right w3-container w3-text-white w3-gray" style="position: fixed; height: 50%; width: 40%;">';
echo '<p>Education:<br /><br />University of Washington ( Fall 2017 - Current ) <br />PhD Student in Computer Science &amp; Engineering<br /> <br /> Mount Holyoke College ( Fall 2013 - Spring 2017 ) <br /> BA in Computer Science &amp; Mathematics ( Summa Cum Laude ) <br /> GPA: 3.97 / 4 <br /></p>';
echo '</div>';
echo '<div class="w3-display-bottomright w3-container w3-black" style="position: fixed; height: 50%; width: 40%;">';
echo '<p>Publications:<br /><br />Ruling the Roost with CNNs: Detecting and Tracking Communal Bird Roosts in Weather Radar Data<br />Zezhou Cheng; <b>Saadia Gabriel</b>; Pankaj Bhambhani; Daniel Sheldon; Subhransu Maji; Andrew Laughlin; David Winkler<br />Fine-Grained Visual Categorization Workshop (FGVC5) at CVPR 2018<br /><br />Ongoing Projects:</p><ul>';
echo '<li>Toxic Language Detection with Neural Logical Reasoning Architectures</li>';
echo '<li>ArXiv Scientific Paper Summarization</li>';
echo '<li>Math Word Problem Solving and Rationale Generation</li>';
echo '</ul><p>Email: skgabrie@cs.washington.edu</p>';
echo '</div>';
echo '<div class="w3-display-bottomleft w3-xxlarge w3-container w3-black" style="position: fixed; bottom: 0; left: 0; height:50px; width: 100%;">';
echo '<a href="https://www.facebook.com/saadia.gabriel.1"><i class="fa fa-facebook-official w3-hover-opacity"></i></a>';
echo '<a href=https://github.com/skgabriel><i class="fa fa-github w3-hover-opacity"></i></a>';
echo '<a href="https://www.linkedin.com/in/saadia-gabriel-97708a103"><i class="fa fa-linkedin w3-hover-opacity"></i></a>';
echo '<font size="1">All content is &copy; 2018&#8208;2020 Saadia Gabriel, all rights reserved.</font>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</body>';
echo '<!-- Footer -->';
echo '';
echo '</html>';
?>